import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import { jsPDF } from 'jspdf';
import { resolveUploadUrl } from '../StudentManagement/uploadUrl';

const API_BASE_URL = 'http://localhost:5000/api/profiles';

const toText = (value) => {
    if (Array.isArray(value)) {
        return value.length > 0 ? value.join(', ') : 'Not provided';
    }
    return value || 'Not provided';
};

function C_StudentProfileView() {
    const { id } = useParams();
    const navigate = useNavigate();
    const [student, setStudent] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');

    useEffect(() => {
        const loadStudentProfile = async () => {
            try {
                const res = await axios.get(`${API_BASE_URL}/${id}`);
                setStudent(res.data);
                setError('');
            } catch (err) {
                setError(err.response?.data?.message || 'Failed to load student profile');
            } finally {
                setLoading(false);
            }
        };

        if (id) {
            loadStudentProfile();
        }
    }, [id]);

    const downloadProfilePdf = () => {
        if (!student) return;

        const doc = new jsPDF({ unit: 'mm', format: 'a4' });
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 15;
        const contentWidth = pageWidth - margin * 2;
        const headerHeight = 24;
        const footerHeight = 12;

        const companyName = localStorage.getItem('companyName') || 'Company User';
        const generatedAt = new Date();
        const generatedAtText = `${generatedAt.toLocaleDateString()} ${generatedAt.toLocaleTimeString()}`;

        let y = headerHeight + 8;

        const drawHeader = () => {
            doc.setDrawColor(40, 40, 40);
            doc.setLineWidth(0.4);
            doc.line(margin, 20, pageWidth - margin, 20);

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(12);
            doc.text('UNIVERSITY INTERNSHIP CAREER MANAGEMENT SYSTEM', margin, 9);

            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            doc.text('Official Student Profile Report', margin, 14);
            doc.text(`Generated By: ${companyName}`, pageWidth - margin, 14, { align: 'right' });
        };

        const drawFooter = () => {
            const pageCount = doc.getNumberOfPages();
            for (let i = 1; i <= pageCount; i += 1) {
                doc.setPage(i);
                doc.setDrawColor(40, 40, 40);
                doc.setLineWidth(0.3);
                doc.line(margin, pageHeight - footerHeight, pageWidth - margin, pageHeight - footerHeight);

                doc.setFont('helvetica', 'normal');
                doc.setFontSize(8);
                doc.text(`Generated: ${generatedAtText}`, margin, pageHeight - 6);
                doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 6, { align: 'right' });
            }
        };

        const ensurePageSpace = (requiredHeight = 8) => {
            const bottomLimit = pageHeight - footerHeight - 6;
            if (y + requiredHeight > bottomLimit) {
                doc.addPage();
                drawHeader();
                y = headerHeight + 8;
            }
        };

        const addSectionTitle = (title) => {
            ensurePageSpace(10);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(11);
            doc.text(title, margin, y);
            y += 2;
            doc.setLineWidth(0.2);
            doc.line(margin, y + 1, pageWidth - margin, y + 1);
            y += 7;
        };

        const addField = (label, value) => {
            const formatted = `${label}: ${toText(value)}`;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            const lines = doc.splitTextToSize(formatted, contentWidth);
            ensurePageSpace(lines.length * 5 + 2);
            doc.text(lines, margin, y);
            y += lines.length * 5 + 2;
        };

        drawHeader();

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text('Student Profile Details', margin, y);
        y += 8;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.text(`Report ID: STU-${student._id || 'N/A'}`, margin, y);
        doc.text(`Report Date: ${generatedAt.toLocaleDateString()}`, pageWidth - margin, y, { align: 'right' });
        y += 7;

        addSectionTitle('1. Personal Information');
        addField('Full Name', `${student.firstName || ''} ${student.lastName || ''}`.trim());
        addField('Email Address', student.email);
        addField('Contact Number', student.contactNumber);
        addField('Province', student.province);
        addField('District', student.district);

        addSectionTitle('2. Academic Information');
        addField('School', student.school);
        addField('A/L Stream', student.localStream);
        addField('Education Level', student.eduLevel);
        addField('University', student.university);
        addField('Degree Program', student.degree);

        addSectionTitle('3. Technical Skill Summary');
        addField('Preferred Field', student.preferredField);
        addField('Frontend Skills', student.frontendSkills);
        addField('Backend Skills', student.backendSkills);
        addField('Database Skills', student.databaseSkills);

        addSectionTitle('4. Additional Details');
        addField('Leadership Experience', student.leadership);
        addField('Awards and Recognition', student.awards);
        addField('Professional Bio', student.bio);

        addSectionTitle('5. Supporting Documents');
        addField('Uploaded CV File', student.cv || 'No CV uploaded');

        ensurePageSpace(12);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9);
        doc.text('This is a system-generated document. No manual signature is required.', margin, y);

        drawFooter();

        doc.save(`${student.firstName || 'student'}_${student.lastName || 'profile'}_profile.pdf`);
    };

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <p className="text-slate-600 dark:text-slate-300">Loading profile...</p>
            </div>
        );
    }

    if (error || !student) {
        return (
            <div className="min-h-screen flex items-center justify-center p-6">
                <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-700">
                    {error || 'Profile not found'}
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-slate-50 px-4 py-8 dark:bg-slate-900">
            <div className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-6 shadow dark:border-slate-700 dark:bg-slate-800">
                <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
                    <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Student Full Profile</h1>
                    <div className="flex gap-3">
                        <button
                            onClick={downloadProfilePdf}
                            className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700"
                        >
                            Download Profile PDF
                        </button>
                        <button
                            onClick={() => navigate(-1)}
                            className="rounded-lg bg-slate-700 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800"
                        >
                            Back
                        </button>
                    </div>
                </div>

                <div className="mb-6 flex flex-col items-center gap-4 sm:flex-row">
                    <img
                        src={student.profileImage ? resolveUploadUrl(student.profileImage) : '/placeholder-profile.png'}
                        alt="student"
                        className="h-24 w-24 rounded-full border-2 border-slate-200 object-cover dark:border-slate-700"
                    />
                    <div>
                        <h2 className="text-xl font-semibold text-slate-900 dark:text-white">
                            {student.firstName} {student.lastName}
                        </h2>
                        <p className="text-slate-600 dark:text-slate-300">{student.email}</p>
                    </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                    <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700">
                        <h3 className="mb-2 font-semibold text-slate-900 dark:text-white">Basic Info</h3>
                        <p><b>Province:</b> {toText(student.province)}</p>
                        <p><b>District:</b> {toText(student.district)}</p>
                        <p><b>Contact:</b> {toText(student.contactNumber)}</p>
                    </div>

                    <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700">
                        <h3 className="mb-2 font-semibold text-slate-900 dark:text-white">Education</h3>
                        <p><b>School:</b> {toText(student.school)}</p>
                        <p><b>A/L Stream:</b> {toText(student.localStream)}</p>
                        <p><b>Level:</b> {toText(student.eduLevel)}</p>
                        <p><b>University:</b> {toText(student.university)}</p>
                        <p><b>Degree:</b> {toText(student.degree)}</p>
                    </div>

                    <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700">
                        <h3 className="mb-2 font-semibold text-slate-900 dark:text-white">Skills</h3>
                        <p><b>Preferred Field:</b> {toText(student.preferredField)}</p>
                        <p><b>Frontend:</b> {toText(student.frontendSkills)}</p>
                        <p><b>Backend:</b> {toText(student.backendSkills)}</p>
                        <p><b>Database:</b> {toText(student.databaseSkills)}</p>
                    </div>

                    <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700">
                        <h3 className="mb-2 font-semibold text-slate-900 dark:text-white">Extra</h3>
                        <p><b>Leadership:</b> {toText(student.leadership)}</p>
                        <p><b>Awards:</b> {toText(student.awards)}</p>
                        <p><b>Bio:</b> {toText(student.bio)}</p>
                    </div>
                </div>

                {student.cv && (
                    <div className="mt-6 rounded-xl border border-slate-200 p-4 dark:border-slate-700">
                        <h3 className="mb-2 font-semibold text-slate-900 dark:text-white">CV</h3>
                        <a
                            href={resolveUploadUrl(student.cv)}
                            target="_blank"
                            rel="noreferrer"
                            className="text-cyan-700 underline dark:text-cyan-300"
                        >
                            Open Uploaded CV
                        </a>
                    </div>
                )}
            </div>
        </div>
    );
}

export default C_StudentProfileView;
